# Generated by Django 2.1 on 2018-08-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('vanue', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Conference', 'Conference'), ('Seminar', 'Seminar'), ('Congress', 'Congress'), ('Course', 'Course')], default='Congress', max_length=100)),
                ('classification', models.CharField(choices=[('Face-to-face', 'Face-to-face'), ('Virtual', 'Virtual')], default='Face-to-face', max_length=100)),
            ],
        ),
    ]
