# Generated by Django 2.1 on 2018-08-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='vanue',
            new_name='venue',
        ),
    ]
